/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package models.administrateur;

import com.formdev.flatlaf.FlatIntelliJLaf;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.UIManager;
import models.Authentification;

/**
 *
 * @author Alfec Informatique 2
 */
public class administrateur_menu extends javax.swing.JFrame {

    /**
     * Creates new form administrateur_ajout
     */
    public administrateur_menu() {
        initComponents();
        this.setResizable(false);
    }
    public void hovenEntered(JLabel label , JPanel panel){
        label.setForeground(Color.decode("#7B170F"));
        
    }
    public void hovenExited(JLabel label , JPanel panel){
        label.setForeground(Color.BLACK);
        
    }
    
    public void hovenpassed(JLabel label , JPanel panel){
        label.setForeground(Color.decode("#7B170F"));
        panel.setBackground(Color.WHITE);
    }
    public void hovenReleased(JLabel label , JPanel panel){
        label.setForeground(Color.BLACK);
        panel.setBackground(Color.decode("#F0F0F0"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        ajoutMenuPanel = new javax.swing.JPanel();
        ajoutMenuLabel = new javax.swing.JLabel();
        modifierMenuPanel = new javax.swing.JPanel();
        modifierMenuLabel = new javax.swing.JLabel();
        listMenuPanel = new javax.swing.JPanel();
        listMenuLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        mainForm = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(240, 240, 240));
        jPanel2.setPreferredSize(new java.awt.Dimension(250, 700));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ajoutMenuPanel.setBackground(new java.awt.Color(240, 240, 240));
        ajoutMenuPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ajoutMenuPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ajoutMenuPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ajoutMenuPanelMouseExited(evt);
            }
        });

        ajoutMenuLabel.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 20)); // NOI18N
        ajoutMenuLabel.setText("Ajouter un agent");

        javax.swing.GroupLayout ajoutMenuPanelLayout = new javax.swing.GroupLayout(ajoutMenuPanel);
        ajoutMenuPanel.setLayout(ajoutMenuPanelLayout);
        ajoutMenuPanelLayout.setHorizontalGroup(
            ajoutMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajoutMenuPanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(ajoutMenuLabel)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        ajoutMenuPanelLayout.setVerticalGroup(
            ajoutMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ajoutMenuLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel2.add(ajoutMenuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 143, 250, 50));

        modifierMenuPanel.setBackground(new java.awt.Color(240, 240, 240));
        modifierMenuPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modifierMenuPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                modifierMenuPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                modifierMenuPanelMouseExited(evt);
            }
        });

        modifierMenuLabel.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 20)); // NOI18N
        modifierMenuLabel.setText("Modifier un agent");

        javax.swing.GroupLayout modifierMenuPanelLayout = new javax.swing.GroupLayout(modifierMenuPanel);
        modifierMenuPanel.setLayout(modifierMenuPanelLayout);
        modifierMenuPanelLayout.setHorizontalGroup(
            modifierMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modifierMenuPanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(modifierMenuLabel)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        modifierMenuPanelLayout.setVerticalGroup(
            modifierMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(modifierMenuLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel2.add(modifierMenuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 193, 250, 50));

        listMenuPanel.setBackground(new java.awt.Color(240, 240, 240));
        listMenuPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listMenuPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                listMenuPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                listMenuPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listMenuPanelMousePressed(evt);
            }
        });

        listMenuLabel.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 20)); // NOI18N
        listMenuLabel.setText("Liste des agents");

        javax.swing.GroupLayout listMenuPanelLayout = new javax.swing.GroupLayout(listMenuPanel);
        listMenuPanel.setLayout(listMenuPanelLayout);
        listMenuPanelLayout.setHorizontalGroup(
            listMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listMenuPanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(listMenuLabel)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        listMenuPanelLayout.setVerticalGroup(
            listMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listMenuLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel2.add(listMenuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 243, 250, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Go Back_60pxW.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 29, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/male_user_60px.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 617, -1, -1));

        jLabel3.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 20)); // NOI18N
        jLabel3.setText("Nom user");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 617, 90, -1));

        jLabel4.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 15)); // NOI18N
        jLabel4.setText("Role");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 646, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        mainForm.setBackground(new java.awt.Color(255, 255, 255));
        mainForm.setLayout(new java.awt.GridLayout(1, 0));
        jPanel1.add(mainForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 950, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ajoutMenuPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajoutMenuPanelMouseEntered
        // TODO add your handling code here:
        hovenEntered(ajoutMenuLabel,ajoutMenuPanel);
    }//GEN-LAST:event_ajoutMenuPanelMouseEntered

    private void ajoutMenuPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajoutMenuPanelMouseExited
        // TODO add your handling code here:
        hovenExited(ajoutMenuLabel,ajoutMenuPanel);
    }//GEN-LAST:event_ajoutMenuPanelMouseExited

    private void modifierMenuPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifierMenuPanelMouseEntered
        // TODO add your handling code here:
        hovenEntered(modifierMenuLabel,modifierMenuPanel);
        
    }//GEN-LAST:event_modifierMenuPanelMouseEntered

    private void modifierMenuPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifierMenuPanelMouseExited
        // TODO add your handling code here:
        hovenExited(modifierMenuLabel,modifierMenuPanel);
    }//GEN-LAST:event_modifierMenuPanelMouseExited

    private void listMenuPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listMenuPanelMousePressed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_listMenuPanelMousePressed

    private void listMenuPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listMenuPanelMouseEntered
        // TODO add your handling code here:
        hovenEntered(listMenuLabel,listMenuPanel);
    }//GEN-LAST:event_listMenuPanelMouseEntered

    private void listMenuPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listMenuPanelMouseExited
        // TODO add your handling code here:
        hovenExited(listMenuLabel,listMenuPanel);
    }//GEN-LAST:event_listMenuPanelMouseExited

    private void ajoutMenuPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajoutMenuPanelMouseClicked
        // TODO add your handling code here:
        
        
        hovenReleased(modifierMenuLabel,modifierMenuPanel);
        hovenReleased(listMenuLabel,listMenuPanel);
        hovenpassed(ajoutMenuLabel,ajoutMenuPanel);
        
        mainForm.removeAll();
        ajouterAgentPanel p=new ajouterAgentPanel();
        mainForm.add(p);
        pack();
        p.setVisible(true);
       
    }//GEN-LAST:event_ajoutMenuPanelMouseClicked

    private void modifierMenuPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifierMenuPanelMouseClicked
        // TODO add your handling code here:
        
        hovenReleased(ajoutMenuLabel,ajoutMenuPanel);
        hovenReleased(listMenuLabel,listMenuPanel);
        hovenpassed(modifierMenuLabel,modifierMenuPanel);
        
        mainForm.removeAll();
        ModifierAgentPanel p=new ModifierAgentPanel();
        mainForm.add(p);
        pack();
        p.setVisible(true);
    }//GEN-LAST:event_modifierMenuPanelMouseClicked

    private void listMenuPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listMenuPanelMouseClicked
        // TODO add your handling code here:
        
        hovenReleased(ajoutMenuLabel,ajoutMenuPanel);
        hovenReleased(modifierMenuLabel,modifierMenuPanel);
        hovenpassed(listMenuLabel,listMenuPanel);
        
        mainForm.removeAll();
        listAgentPanel p=new listAgentPanel();
        mainForm.add(p);
        pack();
        p.setVisible(true);
    }//GEN-LAST:event_listMenuPanelMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        
        Authentification a = new Authentification();
        a.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(administrateur_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(administrateur_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(administrateur_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(administrateur_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        try{
           UIManager.setLookAndFeel(new FlatIntelliJLaf());
           //org.jb2011.lnf.beautyeye.BeautyEyeLNFHelper.launchBeautyEyeLNF();
       } catch (Exception e){
           e.printStackTrace();
       }
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new administrateur_menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ajoutMenuLabel;
    private javax.swing.JPanel ajoutMenuPanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel listMenuLabel;
    private javax.swing.JPanel listMenuPanel;
    private javax.swing.JPanel mainForm;
    private javax.swing.JLabel modifierMenuLabel;
    private javax.swing.JPanel modifierMenuPanel;
    // End of variables declaration//GEN-END:variables
}
