/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package models.agent.sortie;

import models.ClasseVerification;

/**
 *
 * @author Dounia
 */
public class PouletMainSortie extends javax.swing.JPanel {

    ClasseVerification verify = new ClasseVerification();
    
    public PouletMainSortie() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typePoulet = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        idText = new javax.swing.JTextField();
        receptionMain = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        agentSortie = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listAgent = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        poids = new javax.swing.JTextField();
        annulerBtn = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        validerBtn = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        piece = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(912, 576));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        typePoulet.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 20)); // NOI18N
        typePoulet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tenders", "Wings", "Dips", "HotDog" }));
        add(typePoulet, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 25, 170, -1));

        jLabel1.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 20)); // NOI18N
        jLabel1.setText("ID");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 25, 20, 30));

        idText.setBackground(new java.awt.Color(240, 240, 240));
        idText.setPreferredSize(new java.awt.Dimension(64, 30));
        add(idText, new org.netbeans.lib.awtextra.AbsoluteConstraints(614, 25, 260, -1));

        receptionMain.setBackground(new java.awt.Color(240, 240, 240));
        receptionMain.setPreferredSize(new java.awt.Dimension(845, 460));
        receptionMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 16)); // NOI18N
        jLabel2.setText("Agent de sortie");
        jLabel2.setPreferredSize(new java.awt.Dimension(135, 26));
        receptionMain.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 110, -1));

        agentSortie.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        agentSortie.setPreferredSize(new java.awt.Dimension(360, 26));
        agentSortie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                agentSortieKeyPressed(evt);
            }
        });
        receptionMain.add(agentSortie, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 580, 28));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Plus_30px.png"))); // NOI18N
        receptionMain.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 70, -1, -1));

        jScrollPane1.setViewportView(listAgent);

        receptionMain.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 620, 70));

        jLabel6.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 16)); // NOI18N
        jLabel6.setText("Poids ");
        receptionMain.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, 28));

        poids.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 14)); // NOI18N
        poids.setPreferredSize(new java.awt.Dimension(360, 30));
        poids.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                poidsKeyPressed(evt);
            }
        });
        receptionMain.add(poids, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 310, 28));

        annulerBtn.setBackground(new java.awt.Color(223, 66, 53));
        annulerBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(223, 66, 53), 25, true));
        annulerBtn.setOpaque(false);
        annulerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                annulerBtnMouseClicked(evt);
            }
        });
        annulerBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Annuler");
        annulerBtn.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 70, 30));

        receptionMain.add(annulerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 140, 29));

        validerBtn.setBackground(new java.awt.Color(79, 139, 42));
        validerBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(79, 139, 42), 25, true));
        validerBtn.setOpaque(false);
        validerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                validerBtnMouseClicked(evt);
            }
        });
        validerBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Valider");
        validerBtn.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 60, 30));

        receptionMain.add(validerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 280, 140, 29));

        jLabel7.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 16)); // NOI18N
        jLabel7.setText("Pieces ");
        receptionMain.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, -1, 28));

        piece.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 14)); // NOI18N
        piece.setPreferredSize(new java.awt.Dimension(360, 30));
        piece.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pieceKeyPressed(evt);
            }
        });
        receptionMain.add(piece, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, 231, 28));

        add(receptionMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 845, 360));
    }// </editor-fold>//GEN-END:initComponents

    private void agentSortieKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_agentSortieKeyPressed
        verify.verifyCaracter(agentSortie, evt);
    }//GEN-LAST:event_agentSortieKeyPressed

    private void poidsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_poidsKeyPressed
        verify.verifyNamber(poids, evt);
    }//GEN-LAST:event_poidsKeyPressed

    private void annulerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_annulerBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_annulerBtnMouseClicked

    private void validerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_validerBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_validerBtnMouseClicked

    private void pieceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pieceKeyPressed
        verify.verifyNamber(piece, evt);
    }//GEN-LAST:event_pieceKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField agentSortie;
    private javax.swing.JPanel annulerBtn;
    private javax.swing.JTextField idText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listAgent;
    private javax.swing.JTextField piece;
    private javax.swing.JTextField poids;
    private javax.swing.JPanel receptionMain;
    private javax.swing.JComboBox<String> typePoulet;
    private javax.swing.JPanel validerBtn;
    // End of variables declaration//GEN-END:variables
}
