/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package models.stock;

import models.ClasseVerification;

/**
 *
 * @author Alfec Informatique 2
 */
public class parametre_stock extends javax.swing.JFrame {

    ClasseVerification verify = new ClasseVerification ();
    public parametre_stock() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nomStockText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        stockBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        adresseText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        longueurText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        largeurText = new javax.swing.JTextField();
        annulerBtn = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        validerBtn = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        nomStock = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        stockType = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        adresse = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        longueur = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        largeur = new javax.swing.JTextField();
        validerBtn1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        rechercheIcon = new javax.swing.JLabel();

        setTitle("Parametre de stock");
        setPreferredSize(new java.awt.Dimension(920, 540));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(920, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 18)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 16)); // NOI18N
        jLabel1.setText("Nom");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, 30));

        nomStockText.setBackground(new java.awt.Color(240, 240, 240));
        nomStockText.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 14)); // NOI18N
        nomStockText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomStockTextActionPerformed(evt);
            }
        });
        nomStockText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nomStockTextKeyPressed(evt);
            }
        });
        jPanel2.add(nomStockText, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 570, 30));

        jLabel2.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 16)); // NOI18N
        jLabel2.setText("Type de stock");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, 30));

        stockBox.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 14)); // NOI18N
        stockBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chambre froide", "Dépot" }));
        jPanel2.add(stockBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 570, 30));

        jLabel3.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 16)); // NOI18N
        jLabel3.setText("Adresse");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, 30));

        adresseText.setBackground(new java.awt.Color(240, 240, 240));
        adresseText.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 14)); // NOI18N
        adresseText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                adresseTextKeyPressed(evt);
            }
        });
        jPanel2.add(adresseText, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 570, 30));

        jLabel5.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 16)); // NOI18N
        jLabel5.setText("Mesure");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, 30));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 570, 10));

        jLabel4.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 16)); // NOI18N
        jLabel4.setText("Longueur");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, -1, 37));

        longueurText.setBackground(new java.awt.Color(240, 240, 240));
        longueurText.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 14)); // NOI18N
        longueurText.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        longueurText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                longueurTextKeyPressed(evt);
            }
        });
        jPanel2.add(longueurText, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 150, 30));

        jLabel6.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 16)); // NOI18N
        jLabel6.setText("Largeur");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, -1, 37));

        largeurText.setBackground(new java.awt.Color(240, 240, 240));
        largeurText.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 14)); // NOI18N
        largeurText.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        largeurText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                largeurTextKeyPressed(evt);
            }
        });
        jPanel2.add(largeurText, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, 150, 30));

        annulerBtn.setBackground(new java.awt.Color(223, 66, 53));
        annulerBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(223, 66, 53), 25, true));
        annulerBtn.setOpaque(false);
        annulerBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Annuler");
        annulerBtn.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 70, 30));

        jPanel2.add(annulerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 140, 29));

        validerBtn.setBackground(new java.awt.Color(79, 139, 42));
        validerBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(79, 139, 42), 25, true));
        validerBtn.setOpaque(false);
        validerBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Valider");
        validerBtn.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 60, 30));

        jPanel2.add(validerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 360, 140, 29));

        jTabbedPane1.addTab("Ajouter un stock", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(800, 800));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 16)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID stock", "Nom stock", "" }));
        jPanel3.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 120, 30));

        jTextField2.setBackground(new java.awt.Color(240, 240, 240));
        jTextField2.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 14)); // NOI18N
        jTextField2.setPreferredSize(new java.awt.Dimension(360, 30));
        jPanel3.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 370, 30));

        jScrollPane1.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N

        jTable1.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 20)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID stock", "Nom stock", "Type de stock", "Adresse", "Longueur", "Largeur"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(240, 240, 240));
        jTable1.setSelectionBackground(new java.awt.Color(240, 240, 240));
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 770, 168));

        jLabel9.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 16)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Nom stock");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, 30));

        nomStock.setBackground(new java.awt.Color(240, 240, 240));
        nomStock.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 16)); // NOI18N
        nomStock.setPreferredSize(new java.awt.Dimension(360, 30));
        nomStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nomStockKeyPressed(evt);
            }
        });
        jPanel3.add(nomStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 280, 30));

        jLabel10.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 16)); // NOI18N
        jLabel10.setText("Type de Stock");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, 30));

        stockType.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 14)); // NOI18N
        stockType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chambre froide", "Dépot" }));
        jPanel3.add(stockType, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 280, 30));

        jLabel11.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 16)); // NOI18N
        jLabel11.setText("Adresse");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, -1, 30));

        adresse.setBackground(new java.awt.Color(240, 240, 240));
        adresse.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 16)); // NOI18N
        adresse.setPreferredSize(new java.awt.Dimension(360, 30));
        adresse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                adresseKeyPressed(evt);
            }
        });
        jPanel3.add(adresse, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 280, 30));

        jLabel12.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 16)); // NOI18N
        jLabel12.setText("Mesure");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, -1, 30));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, 280, 10));

        jLabel13.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 16)); // NOI18N
        jLabel13.setText("Longueur");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, -1, 30));

        longueur.setBackground(new java.awt.Color(240, 240, 240));
        longueur.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 16)); // NOI18N
        longueur.setPreferredSize(new java.awt.Dimension(360, 30));
        longueur.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                longueurKeyPressed(evt);
            }
        });
        jPanel3.add(longueur, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 310, 200, 30));

        jLabel16.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 16)); // NOI18N
        jLabel16.setText("Largeur");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, -1, 30));

        largeur.setBackground(new java.awt.Color(240, 240, 240));
        largeur.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 16)); // NOI18N
        largeur.setPreferredSize(new java.awt.Dimension(360, 30));
        largeur.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                largeurKeyPressed(evt);
            }
        });
        jPanel3.add(largeur, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 360, 200, 30));

        validerBtn1.setBackground(new java.awt.Color(79, 139, 42));
        validerBtn1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(79, 139, 42), 25, true));
        validerBtn1.setOpaque(false);
        validerBtn1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("MODIFIER");
        validerBtn1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 90, 30));

        jPanel3.add(validerBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 410, 160, 29));

        rechercheIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search_30px.png"))); // NOI18N
        jPanel3.add(rechercheIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, -1, -1));

        jTabbedPane1.addTab("Modifier un stock", jPanel3);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomStockKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomStockKeyPressed
        verify.verifyCaracter(nomStock, evt);
    }//GEN-LAST:event_nomStockKeyPressed

    private void adresseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adresseKeyPressed

        
    }//GEN-LAST:event_adresseKeyPressed

    private void longueurKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_longueurKeyPressed
        verify.verifyNamber(longueur, evt);
    }//GEN-LAST:event_longueurKeyPressed

    private void largeurKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_largeurKeyPressed
        verify.verifyNamber(largeur, evt);
        
    }//GEN-LAST:event_largeurKeyPressed

    private void nomStockTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomStockTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomStockTextActionPerformed

    private void nomStockTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomStockTextKeyPressed
        verify.verifyCaracter(nomStockText, evt);
    }//GEN-LAST:event_nomStockTextKeyPressed

    private void adresseTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adresseTextKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_adresseTextKeyPressed

    private void longueurTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_longueurTextKeyPressed
        verify.verifyNamber(longueurText, evt);
    }//GEN-LAST:event_longueurTextKeyPressed

    private void largeurTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_largeurTextKeyPressed
        verify.verifyNamber(largeurText, evt);
    }//GEN-LAST:event_largeurTextKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(parametre_stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(parametre_stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(parametre_stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(parametre_stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new parametre_stock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adresse;
    private javax.swing.JTextField adresseText;
    private javax.swing.JPanel annulerBtn;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField largeur;
    private javax.swing.JTextField largeurText;
    private javax.swing.JTextField longueur;
    private javax.swing.JTextField longueurText;
    private javax.swing.JTextField nomStock;
    private javax.swing.JTextField nomStockText;
    private javax.swing.JLabel rechercheIcon;
    private javax.swing.JComboBox<String> stockBox;
    private javax.swing.JComboBox<String> stockType;
    private javax.swing.JPanel validerBtn;
    private javax.swing.JPanel validerBtn1;
    // End of variables declaration//GEN-END:variables
}
