/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package models.agent;

/**
 *
 * @author Alfec Informatique 2
 */
public class confirmation extends javax.swing.JFrame {

    /**
     * Creates new form confirmation
     */
    public confirmation() {
        initComponents();
        //fournisseurLab.setText("hello");
    }
    public confirmation(String fournisseur , String acheteur , String recepteur , String TypeBon , String poids , String piece) {
        this.fournisseurLab.setText(fournisseur);
        this.acheteurLab.setText(acheteur);
        this.recepteurLab.setText(recepteur);
        this.typeBonLab.setText(TypeBon);
        this.poidsLab.setText(poids);
        this.pieceLab.setText(piece);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        acheteurLab = new javax.swing.JLabel();
        fournisseurLab = new javax.swing.JLabel();
        recepteurLab = new javax.swing.JLabel();
        poidsLab = new javax.swing.JLabel();
        typeBonLab = new javax.swing.JLabel();
        pieceLab = new javax.swing.JLabel();
        annulerBtn = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        validerBtn = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(123, 23, 15));
        jLabel1.setText("Etes vous sur d'enregistrer ces données:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 17, -1, -1));

        jLabel2.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 16)); // NOI18N
        jLabel2.setText("Fournisseur:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 53, -1, -1));

        jLabel3.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 16)); // NOI18N
        jLabel3.setText("Acheteur:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 86, -1, -1));

        jLabel4.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 16)); // NOI18N
        jLabel4.setText("Recepteur:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 119, -1, 16));

        jLabel5.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 16)); // NOI18N
        jLabel5.setText("Type de bon:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 152, -1, -1));

        jLabel6.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 16)); // NOI18N
        jLabel6.setText("Poids de bon:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 185, -1, -1));

        jLabel7.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 16)); // NOI18N
        jLabel7.setText("Pièces de bon:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 219, -1, -1));

        acheteurLab.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 16)); // NOI18N
        acheteurLab.setToolTipText("  ");
        jPanel1.add(acheteurLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 86, -1, -1));

        fournisseurLab.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 16)); // NOI18N
        fournisseurLab.setText("   ");
        jPanel1.add(fournisseurLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 53, -1, -1));

        recepteurLab.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 16)); // NOI18N
        recepteurLab.setText("  ");
        jPanel1.add(recepteurLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 119, -1, -1));

        poidsLab.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 16)); // NOI18N
        poidsLab.setText("  ");
        poidsLab.setPreferredSize(new java.awt.Dimension(100, 21));
        jPanel1.add(poidsLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 185, -1, -1));

        typeBonLab.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 16)); // NOI18N
        typeBonLab.setText("  ");
        typeBonLab.setToolTipText("  ");
        typeBonLab.setPreferredSize(new java.awt.Dimension(100, 21));
        jPanel1.add(typeBonLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 152, -1, -1));

        pieceLab.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 16)); // NOI18N
        pieceLab.setPreferredSize(new java.awt.Dimension(100, 21));
        jPanel1.add(pieceLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 219, -1, -1));

        annulerBtn.setBackground(new java.awt.Color(223, 66, 53));
        annulerBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(223, 66, 53), 25, true));
        annulerBtn.setOpaque(false);
        annulerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                annulerBtnMouseClicked(evt);
            }
        });
        annulerBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Annuler");
        annulerBtn.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 70, 30));

        jPanel1.add(annulerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 140, 29));

        validerBtn.setBackground(new java.awt.Color(79, 139, 42));
        validerBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(79, 139, 42), 25, true));
        validerBtn.setOpaque(false);
        validerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                validerBtnMouseClicked(evt);
            }
        });
        validerBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Valider");
        validerBtn.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 60, 30));

        jPanel1.add(validerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 140, 29));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void annulerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_annulerBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_annulerBtnMouseClicked

    private void validerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_validerBtnMouseClicked
        
    }//GEN-LAST:event_validerBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(confirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(confirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(confirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(confirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new confirmation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel acheteurLab;
    private javax.swing.JPanel annulerBtn;
    public javax.swing.JLabel fournisseurLab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel pieceLab;
    public javax.swing.JLabel poidsLab;
    public javax.swing.JLabel recepteurLab;
    public javax.swing.JLabel typeBonLab;
    private javax.swing.JPanel validerBtn;
    // End of variables declaration//GEN-END:variables
}
